### ISSUE TITLE
Key label invalid error when uploading files

### ISSUE THREAD

**Issue by majoranimal** [adamws/keyboard-tools#19]
The "Key label invalid" error is throw when any of the attached files are uploaded.

[keyboard-both-hands.json](https://github.com/user-attachments/files/17852964/keyboard-both-hands.json)
[keyboard-right-hand.json](https://github.com/user-attachments/files/17852965/keyboard-right-hand.json)
[keyboard-left-hand.json](https://github.com/user-attachments/files/17852966/keyboard-left-hand.json)

```
Traceback (most recent call last):
File "/kicad/src/tasks.py", line 69, in generate_kicad_project
log_path = kicad.new_pcb(task_id, task_request, __update_percentage)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/kicad/src/kicad.py", line 233, in new_pcb
sanitize_keys(layout["keys"])
File "/kicad/src/kicad.py", line 181, in sanitize_keys
raise RuntimeError(msg)
RuntimeError: Key label invalid: '-2,4' - label needs to follow 'row,column' format, for example '1,2'
```

**Comment by adamws** [comment]
Further development moved to https://github.com/adamws/kle-ng
